import type { Establishment, Queue, Ticket, Notification, User, DailyStats } from "@/types";

export const MOCK_ESTABLISHMENTS: Establishment[] = [
  {
    id: "1",
    slug: "barber-club-maarif",
    name: "Barber Club",
    category: "Coiffure & Barbier",
    address: "45 Bd Zerktouni",
    city: "Mâarif, Casablanca",
    distance: 1.2,
    rating: 4.8,
    reviewCount: 128,
    waitMinutes: 5,
    waitLevel: "low",
    isOpen: true,
    openHours: "09:00 - 21:00",
    imageUrl: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?q=82&w=900&auto=format&fit=crop",
    phone: "+212 6 12 34 56 78",
    email: "contact@barberclub.ma",
    website: "barberclub.ma",
    verified: true,
    services: [
      { id: "s1", name: "Coupe homme", durationMinutes: 20, price: 120, currency: "DH" },
      { id: "s2", name: "Coupe + barbe", durationMinutes: 40, price: 180, currency: "DH" },
      { id: "s3", name: "Coloration", durationMinutes: 90, price: 350, currency: "DH" },
    ],
    coordinates: { lat: 33.59, lng: -7.62 },
  },
  {
    id: "2",
    slug: "spa-marina-anfa",
    name: "Spa Marina",
    category: "Bien-être & Spa",
    address: "12 Rue des Lilas",
    city: "Anfa, Casablanca",
    distance: 2.4,
    rating: 4.6,
    reviewCount: 87,
    waitMinutes: 25,
    waitLevel: "mod",
    isOpen: true,
    openHours: "10:00 - 20:00",
    imageUrl: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?q=80&w=900&auto=format&fit=crop",
    phone: "+212 5 22 98 76 54",
    verified: true,
    services: [
      { id: "s4", name: "Massage relaxant", durationMinutes: 60, price: 350, currency: "DH" },
      { id: "s5", name: "Soin du visage", durationMinutes: 45, price: 250, currency: "DH" },
    ],
    coordinates: { lat: 33.61, lng: -7.64 },
  },
  {
    id: "3",
    slug: "clinique-atlas-racine",
    name: "Clinique Atlas",
    category: "Santé",
    address: "8 Rue Allal Ben Abdellah",
    city: "Racine, Casablanca",
    distance: 3.8,
    rating: 4.2,
    reviewCount: 214,
    waitMinutes: 70,
    waitLevel: "high",
    isOpen: true,
    openHours: "08:00 - 18:00",
    imageUrl: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=900&auto=format&fit=crop",
    phone: "+212 5 22 11 22 33",
    verified: true,
    services: [
      { id: "s6", name: "Consultation générale", durationMinutes: 20 },
      { id: "s7", name: "Consultation spécialiste", durationMinutes: 30 },
      { id: "s8", name: "Analyses", durationMinutes: 15 },
    ],
    coordinates: { lat: 33.58, lng: -7.61 },
  },
  {
    id: "4",
    slug: "prefecture-casablanca",
    name: "Préfecture de Casablanca",
    category: "Administration",
    address: "Pl. Mohammed V",
    city: "Centre-ville, Casablanca",
    distance: 4.1,
    rating: 3.5,
    reviewCount: 456,
    waitMinutes: 45,
    waitLevel: "mod",
    isOpen: true,
    openHours: "08:30 - 16:30",
    imageUrl: "https://images.unsplash.com/photo-1486325212027-8081e485255e?q=82&w=900&auto=format&fit=crop",
    phone: "+212 5 22 27 00 00",
    verified: true,
    services: [
      { id: "s9", name: "État civil", durationMinutes: 10 },
      { id: "s10", name: "Légalisation", durationMinutes: 5 },
      { id: "s11", name: "Certificat de résidence", durationMinutes: 10 },
    ],
    coordinates: { lat: 33.57, lng: -7.60 },
  },
  {
    id: "5",
    slug: "pharmacie-zerktouni",
    name: "Pharmacie Zerktouni",
    category: "Pharmacie",
    address: "127 Bd Zerktouni",
    city: "Mâarif, Casablanca",
    distance: 0.8,
    rating: 4.7,
    reviewCount: 63,
    waitMinutes: 3,
    waitLevel: "low",
    isOpen: true,
    openHours: "08:00 - 23:00",
    imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?q=82&w=900&auto=format&fit=crop",
    phone: "+212 5 22 98 10 20",
    verified: true,
    services: [
      { id: "s12", name: "Conseil pharmaceutique", durationMinutes: 5 },
      { id: "s13", name: "Commande spéciale", durationMinutes: 10 },
    ],
    coordinates: { lat: 33.595, lng: -7.625 },
  },
  {
    id: "6",
    slug: "clinique-californie",
    name: "Clinique Californie",
    category: "Cliniques",
    address: "3 Rue Ibnou Toufail",
    city: "Californie, Casablanca",
    distance: 2.1,
    rating: 4.5,
    reviewCount: 310,
    waitMinutes: 35,
    waitLevel: "mod",
    isOpen: true,
    openHours: "08:00 - 20:00",
    imageUrl: "https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?q=80&w=900&auto=format&fit=crop",
    phone: "+212 5 22 36 36 36",
    verified: true,
    services: [
      { id: "s14", name: "Consultation générale", durationMinutes: 20 },
      { id: "s15", name: "Consultation spécialiste", durationMinutes: 30 },
      { id: "s16", name: "Urgences", durationMinutes: 15 },
    ],
    coordinates: { lat: 33.605, lng: -7.635 },
  },
  {
    id: "7",
    slug: "cabinet-dentaire-sidi-maarouf",
    name: "Cabinet Dr. Idrissi",
    category: "Dentistes",
    address: "22 Rue Bnou Sina",
    city: "Sidi Maarouf, Casablanca",
    distance: 3.2,
    rating: 4.9,
    reviewCount: 94,
    waitMinutes: 10,
    waitLevel: "low",
    isOpen: true,
    openHours: "09:00 - 18:00",
    imageUrl: "https://images.unsplash.com/photo-1606811971618-4486d14f3f99?q=80&w=900&auto=format&fit=crop",
    phone: "+212 6 61 77 88 99",
    verified: true,
    services: [
      { id: "s17", name: "Détartrage", durationMinutes: 30, price: 300, currency: "DH" },
      { id: "s18", name: "Extraction", durationMinutes: 45, price: 500, currency: "DH" },
      { id: "s19", name: "Blanchiment", durationMinutes: 60, price: 1200, currency: "DH" },
    ],
    coordinates: { lat: 33.573, lng: -7.65 },
  },
  {
    id: "8",
    slug: "laboratoire-atlas-analyses",
    name: "Labo Atlas Analyses",
    category: "Laboratoires",
    address: "56 Av. des FAR",
    city: "Centre-ville, Casablanca",
    distance: 4.5,
    rating: 4.3,
    reviewCount: 178,
    waitMinutes: 20,
    waitLevel: "mod",
    isOpen: true,
    openHours: "07:00 - 17:00",
    imageUrl: "https://images.unsplash.com/photo-1530026405186-ed1f139313f8?q=80&w=900&auto=format&fit=crop",
    phone: "+212 5 22 44 55 66",
    verified: true,
    services: [
      { id: "s20", name: "Prise de sang", durationMinutes: 10, price: 80, currency: "DH" },
      { id: "s21", name: "Bilan complet", durationMinutes: 15, price: 350, currency: "DH" },
    ],
    coordinates: { lat: 33.592, lng: -7.612 },
  },
  {
    id: "9",
    slug: "garage-mecanique-bouskoura",
    name: "Garage Auto Bouskoura",
    category: "Garages",
    address: "Route de Bouskoura",
    city: "Bouskoura, Casablanca",
    distance: 7.3,
    rating: 4.1,
    reviewCount: 55,
    waitMinutes: 50,
    waitLevel: "mod",
    isOpen: true,
    openHours: "08:00 - 19:00",
    imageUrl: "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?q=80&w=900&auto=format&fit=crop",
    phone: "+212 6 70 12 34 56",
    verified: false,
    services: [
      { id: "s22", name: "Vidange", durationMinutes: 30, price: 250, currency: "DH" },
      { id: "s23", name: "Révision complète", durationMinutes: 120, price: 900, currency: "DH" },
      { id: "s24", name: "Climatisation", durationMinutes: 60, price: 600, currency: "DH" },
    ],
    coordinates: { lat: 33.548, lng: -7.681 },
  },
  {
    id: "10",
    slug: "lavage-auto-aïn-chock",
    name: "Clean Car Express",
    category: "Lavage auto",
    address: "Bd Aïn Chock",
    city: "Aïn Chock, Casablanca",
    distance: 5.6,
    rating: 4.4,
    reviewCount: 42,
    waitMinutes: 8,
    waitLevel: "low",
    isOpen: true,
    openHours: "08:00 - 21:00",
    imageUrl: "https://images.unsplash.com/photo-1545327126-01f97f00b16e?q=80&w=900&auto=format&fit=crop",
    phone: "+212 6 55 43 21 09",
    verified: false,
    services: [
      { id: "s25", name: "Lavage extérieur", durationMinutes: 15, price: 50, currency: "DH" },
      { id: "s26", name: "Lavage intérieur + ext.", durationMinutes: 30, price: 100, currency: "DH" },
      { id: "s27", name: "Polish & cire", durationMinutes: 90, price: 400, currency: "DH" },
    ],
    coordinates: { lat: 33.561, lng: -7.655 },
  },
];

export const MOCK_QUEUES: Queue[] = [
  {
    id: "q1",
    establishmentId: "1",
    serviceId: "s1",
    serviceName: "Coupe homme",
    label: "A",
    currentTicket: "A-012",
    waitingCount: 3,
    estimatedWaitMinutes: 5,
    isOpen: true,
    servedToday: 27,
  },
  {
    id: "q2",
    establishmentId: "4",
    serviceId: "s9",
    serviceName: "État civil",
    label: "A",
    currentTicket: "A-045",
    waitingCount: 7,
    estimatedWaitMinutes: 28,
    isOpen: true,
    servedToday: 45,
  },
  {
    id: "q3",
    establishmentId: "4",
    serviceId: "s10",
    serviceName: "Légalisation",
    label: "B",
    currentTicket: "B-012",
    waitingCount: 5,
    estimatedWaitMinutes: 20,
    isOpen: true,
    servedToday: 30,
  },
];

export const MOCK_TICKET: Ticket = {
  id: "t1",
  number: "A-052",
  queueId: "q1",
  establishmentId: "1",
  establishmentSlug: "barber-club-maarif",
  establishmentName: "Barber Club",
  serviceName: "Coupe homme",
  position: 3,
  estimatedWaitMinutes: 7,
  estimatedTime: "14:32",
  status: "waiting",
  createdAt: new Date().toISOString(),
};

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    type: "turn",
    title: "C'est bientôt votre tour !",
    body: "Plus que 2 personnes avant vous chez Barber Club",
    read: false,
    createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    establishmentId: "1",
  },
  {
    id: "n2",
    type: "reminder",
    title: "Votre rendez-vous approche",
    body: "Rappelez-vous de votre passage chez Spa Marina dans 30 min",
    read: false,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    establishmentId: "2",
  },
  {
    id: "n3",
    type: "promo",
    title: "Offre spéciale",
    body: "Barber Club vous offre 20% sur votre prochaine visite",
    read: true,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    establishmentId: "1",
  },
  {
    id: "n4",
    type: "system",
    title: "Bienvenue sur Tornoo !",
    body: "Découvrez tous les établissements autour de vous",
    read: true,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_USER: User = {
  id: "u1",
  name: "Amine Benali",
  email: "amine@example.com",
  phone: "+212 6 12 34 56 78",
  role: "client",
  favorites: ["1", "2"],
};

export const MOCK_DAILY_STATS: DailyStats[] = [
  { date: "2024-01-01", clientsServed: 24, avgWaitMinutes: 18, revenue: 1440, peakHour: "11h - 12h" },
  { date: "2024-01-02", clientsServed: 31, avgWaitMinutes: 22, revenue: 1860, peakHour: "14h - 15h" },
  { date: "2024-01-03", clientsServed: 19, avgWaitMinutes: 15, revenue: 1140, peakHour: "10h - 11h" },
  { date: "2024-01-04", clientsServed: 28, avgWaitMinutes: 20, revenue: 1680, peakHour: "11h - 12h" },
  { date: "2024-01-05", clientsServed: 35, avgWaitMinutes: 25, revenue: 2100, peakHour: "12h - 13h" },
  { date: "2024-01-06", clientsServed: 22, avgWaitMinutes: 17, revenue: 1320, peakHour: "15h - 16h" },
  { date: "2024-01-07", clientsServed: 18, avgWaitMinutes: 14, revenue: 1080, peakHour: "10h - 11h" },
];
